/**
 * @license
 * SPDX-License-Identifier: Apache-2.0
 */

export const OUTLETS = [
  { id: '31', name: 'Sec 31' },
  { id: '42', name: 'Sec 42' },
  { id: '35', name: 'Sec 35' },
  { id: '88', name: 'Sec 88' },
  { id: 'bk', name: 'Base Kitchen' }
];

export interface Item {
  id: string;
  name: string;
  category: string;
  barcode?: string;
  status?: string;
}

export const INITIAL_ITEMS: Item[] = [
  { id: '1', category: 'Beverages', name: 'Black Coffee', barcode: 'BR000001' },
  { id: '2', category: 'Beverages', name: 'Cafe Mocha', barcode: 'BR000002' },
  { id: '3', category: 'Beverages', name: 'Cappuccino', barcode: 'BR000003' },
  { id: '4', category: 'Beverages', name: 'Classic Cold Coffee', barcode: 'BR000004' },
  { id: '5', category: 'Beverages', name: 'Coke Small bottle', barcode: 'BR000005' },
  { id: '6', category: 'Beverages', name: 'Diet Coke Can', barcode: 'BR000006' },
  { id: '7', category: 'Beverages', name: 'Espresso', barcode: 'BR000007' },
  { id: '8', category: 'Beverages', name: 'Fresh Lime Soda', barcode: 'BR000008' },
  { id: '9', category: 'Beverages', name: 'Ice Latte', barcode: 'BR000009' },
  { id: '10', category: 'Beverages', name: 'Lemon Ice Tea', barcode: 'BR000010' },
  { id: '11', category: 'Beverages', name: 'Mocktail Passion Fruit & Basil Mojito', barcode: 'BR000011' },
  { id: '12', category: 'Beverages', name: 'Mocktail Spiced Jamun Mojito', barcode: 'BR000012' },
  { id: '13', category: 'Beverages', name: 'Mocktail Virgin Mojito', barcode: 'BR000013' },
  { id: '14', category: 'Beverages', name: 'Sprite bottle', barcode: 'BR000014' },
  { id: '15', category: 'Beverages', name: 'Thumsup bottle', barcode: 'BR000015' },
  { id: '16', category: 'Breads', name: 'Brown Bread', barcode: 'BR000016' },
  { id: '17', category: 'Breads', name: 'Burger Bun', barcode: 'BR000017' },
  { id: '18', category: 'Breads', name: 'Garlic Loaf', barcode: 'BR000018' },
  { id: '19', category: 'Breads', name: 'Jumbo Bread', barcode: 'BR000019' },
  { id: '20', category: 'Breads', name: 'Milk Bread', barcode: 'BR000020' },
  { id: '21', category: 'Breads', name: 'Milk Pao Bun', barcode: 'BR000021' },
  { id: '22', category: 'Breads', name: 'Mini Croisant', barcode: 'BR000022' },
  { id: '23', category: 'Breads', name: 'Multigrain Bread', barcode: 'BR000023' },
  { id: '24', category: 'Breads', name: 'Multigrain Jumbo Bread', barcode: 'BR000024' },
  { id: '25', category: 'Breads', name: 'Multigrain Loaf', barcode: 'BR000025' },
  { id: '26', category: 'Breads', name: 'Pao Bun', barcode: 'BR000026' },
  { id: '27', category: 'Breads', name: 'Pizza Base (pack Of 2)', barcode: 'BR000027' },
  { id: '28', category: 'Breads', name: 'White Bread', barcode: 'BR000028' },
  { id: '29', category: 'Breads', name: 'Whole Wheat Bread', barcode: 'BR000029' },
  { id: '30', category: 'Breads', name: 'Whole Wheat Burger Bun', barcode: 'BR000030' },
  { id: '31', category: 'Cake Jars', name: 'Banoffee Pie Jar', barcode: 'BR000031' },
  { id: '32', category: 'Cake Jars', name: 'Bluebarry Jar', barcode: 'BR000032' },
  { id: '33', category: 'Cake Jars', name: 'Blueberry Jar', barcode: 'BR000033' },
  { id: '34', category: 'Cake Jars', name: 'Chocolate Truffle Jar', barcode: 'BR000034' },
  { id: '35', category: 'Cake Jars', name: 'Lotus Biscoff Dessert Tub', barcode: 'BR000035' },
  { id: '36', category: 'Cake Jars', name: 'Nutella Jar', barcode: 'BR000036' },
  { id: '37', category: 'Cake Jars', name: 'Rasmalai Jar', barcode: 'BR000037' },
  { id: '38', category: 'Cake Jars', name: 'Red Velvet Jar', barcode: 'BR000038' },
  { id: '39', category: 'Cake Jars', name: 'Tiramisu Dessert Tub', barcode: 'BR000039' },
  { id: '40', category: 'Cheese Cakes', name: 'Banoffee Pie Cheese Cake (1 Kg - Serve 8-10)', barcode: 'BR000040' },
  { id: '41', category: 'Cheese Cakes', name: 'Banoffee Pie Cheese Cake (1/2 Kg - Serve 4-6)', barcode: 'BR000041' },
  { id: '42', category: 'Cheese Cakes', name: 'Blueberry Cheese Cake (1 Kg - Serve 8-10)', barcode: 'BR000042' },
  { id: '43', category: 'Cheese Cakes', name: 'Blueberry Cheese Cake (1/2 Kg - Serve 4-6)', barcode: 'BR000043' },
  { id: '44', category: 'Cheese Cakes', name: 'Lotus Biscoff Cheese Cake (1 Kg - Serve 8-10)', barcode: 'BR000044' },
  { id: '45', category: 'Cheese Cakes', name: 'Lotus Biscoff Cheese Cake (1/2 Kg - Serve 4-6)', barcode: 'BR000045' },
  { id: '46', category: 'Cheese Cakes', name: 'Mix Berry Cheese Cake (1 Kg - Serve 8-10)', barcode: 'BR000046' },
  { id: '47', category: 'Cheese Cakes', name: 'Mix Berry Cheese Cake (1/2 Kg - Serve 4-6)', barcode: 'BR000047' },
  { id: '48', category: 'Cheese Cakes', name: 'New York Cheese Cake (1 Kg - Serve 8-10)', barcode: 'BR000048' },
  { id: '49', category: 'Cheese Cakes', name: 'New York Cheese Cake (1/2 Kg - Serve 4-6)', barcode: 'BR000049' },
  { id: '50', category: 'Cheese Cakes', name: 'Nutella Cheese Cake (1 Kg - Serve 8-10)', barcode: 'BR000050' },
  { id: '51', category: 'Cheese Cakes', name: 'Nutella Cheese Cake (1/2 Kg - Serve 4-6)', barcode: 'BR000051' },
  { id: '52', category: 'Cheese Cakes', name: 'Strawberry Cheese Cake', barcode: 'BR000052' },
  { id: '53', category: 'Chips/Namkeens', name: 'Chips Beetroot', barcode: 'BR000053' },
  { id: '54', category: 'Chips/Namkeens', name: 'Chips Biryani', barcode: 'BR000054' },
  { id: '55', category: 'Chips/Namkeens', name: 'Chips Broccoli', barcode: 'BR000055' },
  { id: '56', category: 'Chips/Namkeens', name: 'Chips Finger Millet', barcode: 'BR000056' },
  { id: '57', category: 'Chips/Namkeens', name: 'Chips Mix Veg', barcode: 'BR000057' },
  { id: '58', category: 'Chips/Namkeens', name: 'Chips Oats', barcode: 'BR000058' },
  { id: '59', category: 'Chips/Namkeens', name: 'Chips Quinoa', barcode: 'BR000059' },
  { id: '60', category: 'Chips/Namkeens', name: 'Chips Rosted Millet', barcode: 'BR000060' },
  { id: '61', category: 'Chips/Namkeens', name: 'Chips Sorghum', barcode: 'BR000061' },
  { id: '62', category: 'Chocolates', name: 'Almond Coated Jar', barcode: 'BR000062' },
  { id: '63', category: 'Chocolates', name: 'Big Cage Chocolate Jar', barcode: 'BR000063' },
  { id: '64', category: 'Chocolates', name: 'Butterscotch Chocolate', barcode: 'BR000064' },
  { id: '65', category: 'Chocolates', name: 'Chocolate 12 Cavity Chocolate Box', barcode: 'BR000065' },
  { id: '66', category: 'Chocolates', name: 'Chocolate Bar', barcode: 'BR000066' },
  { id: '67', category: 'Chocolates', name: 'Chocolate Lollypop', barcode: 'BR000067' },
  { id: '68', category: 'Chocolates', name: 'Crackle Chocolate', barcode: 'BR000068' },
  { id: '69', category: 'Chocolates', name: 'Crystal Box 25 Cavity', barcode: 'BR000069' },
  { id: '70', category: 'Chocolates', name: 'Dark Chocolate', barcode: 'BR000070' },
  { id: '71', category: 'Chocolates', name: 'Fruit And Nut', barcode: 'BR000071' },
  { id: '72', category: 'Chocolates', name: 'Heart Chocolate', barcode: 'BR000072' },
  { id: '73', category: 'Chocolates', name: 'Kaju Jar', barcode: 'BR000073' },
  { id: '74', category: 'Chocolates', name: 'Pan Chocolate', barcode: 'BR000074' },
  { id: '75', category: 'Chocolates', name: 'Pistachio Fudge', barcode: 'BR000075' },
  { id: '76', category: 'Chocolates', name: 'Smile Chocolate Box', barcode: 'BR000076' },
  { id: '77', category: 'Chocolates', name: 'Toffee', barcode: 'BR000077' },
  { id: '78', category: 'Classic Cakes', name: 'Black Forest Cake (1 Kg - Serve 8-10)', barcode: 'BR000078' },
  { id: '79', category: 'Classic Cakes', name: 'Black Forest Cake (1/2 Kg - Serve 4-6)', barcode: 'BR000079' },
  { id: '80', category: 'Classic Cakes', name: 'Blueberry Cake (1 Kg - Serve 8-10)', barcode: 'BR000080' },
  { id: '81', category: 'Classic Cakes', name: 'Blueberry Cake (1/2 Kg - Serve 4-6)', barcode: 'BR000081' },
  { id: '82', category: 'Classic Cakes', name: 'Butterscotch Cake (1 Kg - Serve 8-10)', barcode: 'BR000082' },
  { id: '83', category: 'Classic Cakes', name: 'Butterscotch Cake (1/2 Kg - Serve 4-6)', barcode: 'BR000083' },
  { id: '84', category: 'Classic Cakes', name: 'Chocolate Truffle Cake (1 Kg)', barcode: 'BR000084' },
  { id: '85', category: 'Classic Cakes', name: 'Chocolate Truffle Cake (1/2 Kg)', barcode: 'BR000085' },
  { id: '86', category: 'Classic Cakes', name: 'Classic Pineapple Cake (1 Kg - Serve 8-10)', barcode: 'BR000086' },
  { id: '87', category: 'Classic Cakes', name: 'Classic Pineapple Cake (1/2 Kg - Serve 4-6)', barcode: 'BR000087' },
  { id: '88', category: 'Classic Cakes', name: 'Fresh Fruit Cake (1 Kg - Serve 8-10)', barcode: 'BR000088' },
  { id: '89', category: 'Classic Cakes', name: 'Fresh Fruit Cake (1/2 Kg - Serve 4-6)', barcode: 'BR000089' },
  { id: '90', category: 'Classic Cakes', name: 'Fresh Mango (Seasonal) Cake (1 Kg - Serve 8-10)', barcode: 'BR000090' },
  { id: '91', category: 'Classic Cakes', name: 'Fresh Mango (Seasonal) Cake (1/2 Kg - Serve 4-6)', barcode: 'BR000091' },
  { id: '92', category: 'Classic Cakes', name: 'Fresh Strawberry (Seasonal) Cake Large', barcode: 'BR000092' },
  { id: '93', category: 'Classic Cakes', name: 'Rainbow Cake Large', barcode: 'BR000093' },
  { id: '94', category: 'Classic Cakes', name: 'Red Velvet Cake (1 Kg - Serve 8-10)', barcode: 'BR000094' },
  { id: '95', category: 'Classic Cakes', name: 'Red Velvet Cake (1/2 Kg - Serve 4-6)', barcode: 'BR000095' },
  { id: '96', category: 'Classic Cakes', name: 'Vanilla Cake (1 Kg - Serve 8-10)', barcode: 'BR000096' },
  { id: '97', category: 'Classic Cakes', name: 'Vanilla Cake (1/2 Kg - Serve 4-6)', barcode: 'BR000097' },
  { id: '98', category: 'Classic Cakes', name: 'White Forest Cake (1 Kg)', barcode: 'BR000098' },
  { id: '99', category: 'Classic Cakes', name: 'White Forest Cake (1/2 Kg)', barcode: 'BR000099' },
  { id: '101', category: 'Cookies & Snacks', name: 'Almond Biscooti', barcode: 'BR000101' },
  { id: '102', category: 'Cookies & Snacks', name: 'American Almond Cookies', barcode: 'BR000102' },
  { id: '103', category: 'Cookies & Snacks', name: 'Anzac Cookies', barcode: 'BR000103' },
  { id: '104', category: 'Cookies & Snacks', name: 'Besan Khatai', barcode: 'BR000104' },
  { id: '105', category: 'Cookies & Snacks', name: 'Butter Kaju', barcode: 'BR000105' },
  { id: '106', category: 'Cookies & Snacks', name: 'Cake Rusk', barcode: 'BR000106' },
  { id: '107', category: 'Cookies & Snacks', name: 'Cheese Cracker', barcode: 'BR000107' },
  { id: '108', category: 'Cookies & Snacks', name: 'Cheese Straw', barcode: 'BR000108' },
  { id: '109', category: 'Cookies & Snacks', name: 'Coconut Macroons', barcode: 'BR000109' },
  { id: '110', category: 'Cookies & Snacks', name: 'Cookies', barcode: 'BR000110' },
  { id: '111', category: 'Cookies & Snacks', name: 'Desi Ghee Aata Cookies', barcode: 'BR000111' },
  { id: '112', category: 'Cookies & Snacks', name: 'Double Choco Chips', barcode: 'BR000112' },
  { id: '113', category: 'Cookies & Snacks', name: 'French Hearts', barcode: 'BR000113' },
  { id: '114', category: 'Cookies & Snacks', name: 'Garlic Bread Toast', barcode: 'BR000114' },
  { id: '115', category: 'Cookies & Snacks', name: 'Jeera Sticks', barcode: 'BR000115' },
  { id: '116', category: 'Cookies & Snacks', name: 'Kaju Pista', barcode: 'BR000116' },
  { id: '117', category: 'Cookies & Snacks', name: 'Lavash', barcode: 'BR000117' },
  { id: '118', category: 'Cookies & Snacks', name: 'Methi Puff', barcode: 'BR000118' },
  { id: '119', category: 'Cookies & Snacks', name: 'Mocha Cookie', barcode: 'BR000119' },
  { id: '120', category: 'Cookies & Snacks', name: 'Muesli Cookies', barcode: 'BR000120' },
  { id: '121', category: 'Cookies & Snacks', name: 'Multigrain Cookies', barcode: 'BR000121' },
  { id: '122', category: 'Cookies & Snacks', name: 'Oatmeal Cookies', barcode: 'BR000122' },
  { id: '123', category: 'Cookies & Snacks', name: 'Pista Khati', barcode: 'BR000123' },
  { id: '124', category: 'Cookies & Snacks', name: 'Raagi Chips', barcode: 'BR000124' },
  { id: '125', category: 'Cookies & Snacks', name: 'Raagi Crips', barcode: 'BR000125' },
  { id: '126', category: 'Cookies & Snacks', name: 'Ragi Gluten Free', barcode: 'BR000126' },
  { id: '127', category: 'Cookies & Snacks', name: 'Red Velvet Cookies', barcode: 'BR000127' },
  { id: '128', category: 'Cookies & Snacks', name: 'Soup Stick', barcode: 'BR000128' },
  { id: '129', category: 'Customised Cakes', name: 'Custom Cake', barcode: 'BR000129' },
  { id: '130', category: 'Customised Cakes', name: 'Full Fondant', barcode: 'BR000130' },
  { id: '131', category: 'Customised Cakes', name: 'Photo Cake (1 Kg - Serve 8-10)', barcode: 'BR000131' },
  { id: '132', category: 'Customised Cakes', name: 'Photo Cake (1/2 Kg - Serve 4-6)', barcode: 'BR000132' },
  { id: '133', category: 'Customised Cakes', name: 'Semi Fondant', barcode: 'BR000133' },
  { id: '134', category: 'Decorations', name: 'Anniversary Banner', barcode: 'BR000134' },
  { id: '135', category: 'Decorations', name: 'BALLON big ballon', barcode: 'BR000135' },
  { id: '136', category: 'Decorations', name: 'birthday banner', barcode: 'BR000136' },
  { id: '137', category: 'Decorations', name: 'Birthday Caps', barcode: 'BR000137' },
  { id: '138', category: 'Decorations', name: 'Cake Topper', barcode: 'BR000138' },
  { id: '139', category: 'Decorations', name: 'Candle', barcode: 'BR000139' },
  { id: '140', category: 'Decorations', name: 'Crown', barcode: 'BR000140' },
  { id: '141', category: 'Decorations', name: 'Foil Balllon', barcode: 'BR000141' },
  { id: '142', category: 'Decorations', name: 'Foil Fring curtains', barcode: 'BR000142' },
  { id: '143', category: 'Decorations', name: 'Golden Number Candle', barcode: 'BR000143' },
  { id: '144', category: 'Decorations', name: 'Golden Tiara', barcode: 'BR000144' },
  { id: '145', category: 'Decorations', name: 'golden/Sliver Spiral', barcode: 'BR000145' },
  { id: '146', category: 'Decorations', name: 'Normal Candles', barcode: 'BR000146' },
  { id: '147', category: 'Decorations', name: 'Poppers Big', barcode: 'BR000147' },
  { id: '148', category: 'Decorations', name: 'Poppers small', barcode: 'BR000148' },
  { id: '149', category: 'Decorations', name: 'Sashes', barcode: 'BR000149' },
  { id: '150', category: 'Decorations', name: 'Sparkle Candle', barcode: 'BR000150' },
  { id: '151', category: 'Dry Fruits & Dry Cakes', name: 'Chocochip (1 Kg - Serve 8-10)', barcode: 'BR000151' },
  { id: '152', category: 'Dry Fruits & Dry Cakes', name: 'Chocochip (1/2 Kg - Serve 4-6)', barcode: 'BR000152' },
  { id: '153', category: 'Dry Fruits & Dry Cakes', name: 'Chocochip (250g)', barcode: 'BR000153' },
  { id: '154', category: 'Dry Fruits & Dry Cakes', name: 'Date&Walnut (1 Kg - Serve 8-10)', barcode: 'BR000154' },
  { id: '155', category: 'Dry Fruits & Dry Cakes', name: 'Date&Walnut (1/2 Kg - Serve 4-6)', barcode: 'BR000155' },
  { id: '156', category: 'Dry Fruits & Dry Cakes', name: 'Date&Walnut (250g)', barcode: 'BR000156' },
  { id: '157', category: 'Dry Fruits & Dry Cakes', name: 'Honeyalmond (1 Kg - Serve 8-10)', barcode: 'BR000157' },
  { id: '158', category: 'Dry Fruits & Dry Cakes', name: 'Honeyalmond (1/2 Kg - Serve 4-6)', barcode: 'BR000158' },
  { id: '159', category: 'Dry Fruits & Dry Cakes', name: 'Honeyalmond (250g)', barcode: 'BR000159' },
  { id: '160', category: 'Dry Fruits & Dry Cakes', name: 'Mawa (1 Kg - Serve 8-10)', barcode: 'BR000160' },
  { id: '161', category: 'Dry Fruits & Dry Cakes', name: 'Mawa (1/2 Kg - Serve 4-6)', barcode: 'BR000161' },
  { id: '162', category: 'Dry Fruits & Dry Cakes', name: 'Mawa (250g)', barcode: 'BR000162' },
  { id: '163', category: 'Dry Fruits & Dry Cakes', name: 'Plum (1 Kg - Serve 8-10)', barcode: 'BR000163' },
  { id: '164', category: 'Dry Fruits & Dry Cakes', name: 'Plum (1/2 Kg - Serve 4-6)', barcode: 'BR000164' },
  { id: '165', category: 'Dry Fruits & Dry Cakes', name: 'Plum (250g)', barcode: 'BR000165' },
  { id: '166', category: 'Exotic Cakes', name: 'Belgium Choco Crunch (1 Kg - Serve 8-10)', barcode: 'BR000166' },
  { id: '167', category: 'Exotic Cakes', name: 'Belgium Choco Crunch (1/2 Kg - Serve 4-6)', barcode: 'BR000167' },
  { id: '168', category: 'Exotic Cakes', name: 'Christmas Chocolate Cake', barcode: 'BR000168' },
  { id: '169', category: 'Exotic Cakes', name: 'Ferraro Rocher Cake (1 Kg - Serve 8-10)', barcode: 'BR000169' },
  { id: '170', category: 'Exotic Cakes', name: 'Ferraro Rocher Cake (1/2 Kg - Serve 4-6)', barcode: 'BR000170' },
  { id: '171', category: 'Exotic Cakes', name: 'Kit-Kat Gems Cake (1 Kg - Serve 8-10)', barcode: 'BR000171' },
  { id: '172', category: 'Exotic Cakes', name: 'Kit-Kat Gems Cake (1/2 Kg - Serve 4-6)', barcode: 'BR000172' },
  { id: '173', category: 'Exotic Cakes', name: 'Lotus Biscoff Cake (1 Kg - Serve 8-10)', barcode: 'BR000173' },
  { id: '174', category: 'Exotic Cakes', name: 'Lotus Biscoff Cake (1/2 Kg - Serve 4-6)', barcode: 'BR000174' },
  { id: '175', category: 'Exotic Cakes', name: 'Nutella Strawberry Cake', barcode: 'BR000175' },
  { id: '176', category: 'Exotic Cakes', name: 'Rasmalai (1 Kg - Serve 8-10)', barcode: 'BR000176' },
  { id: '177', category: 'Exotic Cakes', name: 'Rasmalai (1/2 Kg - Serve 4-6)', barcode: 'BR000177' },
  { id: '178', category: 'Exotic Cakes', name: 'Rose & Pistacho Cake (1 Kg - Serve 8-10)', barcode: 'BR000178' },
  { id: '179', category: 'Exotic Cakes', name: 'Rose & Pistacho Cake (1/2 Kg - Serve 4-6)', barcode: 'BR000179' },
  { id: '180', category: 'Exotic Cakes', name: 'Santa Claus Pineapple Cake', barcode: 'BR000180' },
  { id: '181', category: 'Exotic Cakes', name: 'Tiramisu (Coffee Flavour) (1 Kg - Serve 8-10)', barcode: 'BR000181' },
  { id: '182', category: 'Exotic Cakes', name: 'Tiramisu (Coffee Flavour) (1/2 Kg - Serve 4-6)', barcode: 'BR000182' },
  { id: '183', category: 'Fries & Nachos', name: 'Fries Classic Salted', barcode: 'BR000183' },
  { id: '184', category: 'Fries & Nachos', name: 'Fries Peri-peri', barcode: 'BR000184' },
  { id: '185', category: 'Fries & Nachos', name: 'Fries Peri Peri Cheesy Beked', barcode: 'BR000185' },
  { id: '186', category: 'Garlic Bread', name: 'Cheese Garlic Bread', barcode: 'BR000186' },
  { id: '187', category: 'Garlic Bread', name: 'Exotic Garlic Bread', barcode: 'BR000187' },
  { id: '188', category: 'Garlic Bread', name: 'Paneer Garlic Bread', barcode: 'BR000188' },
  { id: '189', category: 'Gift Packs & Hampers', name: 'Big Dry Fruit Box', barcode: 'BR000189' },
  { id: '190', category: 'Gift Packs & Hampers', name: 'Big Paper Packing Chocolate Box', barcode: 'BR000190' },
  { id: '191', category: 'Gift Packs & Hampers', name: 'Big Snack Box', barcode: 'BR000191' },
  { id: '192', category: 'Gift Packs & Hampers', name: 'Bookey Paper Packing Chocolate Box', barcode: 'BR000192' },
  { id: '193', category: 'Gift Packs & Hampers', name: 'Chocolate Packing', barcode: 'BR000193' },
  { id: '194', category: 'Gift Packs & Hampers', name: 'Coated Nuts 3 Jar', barcode: 'BR000194' },
  { id: '195', category: 'Gift Packs & Hampers', name: 'Coated Nuts Brownie Box', barcode: 'BR000195' },
  { id: '196', category: 'Gift Packs & Hampers', name: 'Coated Nuts Square', barcode: 'BR000196' },
  { id: '197', category: 'Gift Packs & Hampers', name: 'Coated Nuts Wooden Choco Box', barcode: 'BR000197' },
  { id: '198', category: 'Gift Packs & Hampers', name: 'Customised Hamper', barcode: 'BR000198' },
  { id: '199', category: 'Gift Packs & Hampers', name: 'Heart Box', barcode: 'BR000199' },
  { id: '200', category: 'Gift Packs & Hampers', name: 'Premium Choco.Box', barcode: 'BR000200' },
  { id: '201', category: 'Gift Packs & Hampers', name: 'Semi Big Wooden Basket', barcode: 'BR000201' },
  { id: '202', category: 'Gift Packs & Hampers', name: 'Small Cage 2 Jar', barcode: 'BR000202' },
  { id: '203', category: 'Gift Packs & Hampers', name: 'Small Dry Fruit Box', barcode: 'BR000203' },
  { id: '204', category: 'Gift Packs & Hampers', name: 'Small Paper Packing', barcode: 'BR000204' },
  { id: '205', category: 'Gift Packs & Hampers', name: 'Small Square Wooden Basket', barcode: 'BR000205' },
  { id: '206', category: 'Gift Packs & Hampers', name: 'Smile Box', barcode: 'BR000206' },
  { id: '207', category: 'Gift Packs & Hampers', name: 'Toffee Packing', barcode: 'BR000207' },
  { id: '208', category: 'Others', name: 'Alloo Patty', barcode: 'BR000208' },
  { id: '209', category: 'Others', name: 'Micro Bun', barcode: 'BR000209' },
  { id: '210', category: 'Pastries', name: 'Apple Pie', barcode: 'BR000210' },
  { id: '211', category: 'Pastries', name: 'Banoffi Pie Chesse Pastry', barcode: 'BR000211' },
  { id: '212', category: 'Pastries', name: 'Biscoff Cheese Pastry', barcode: 'BR000212' },
  { id: '213', category: 'Pastries', name: 'Black Forest Pastry', barcode: 'BR000213' },
  { id: '214', category: 'Pastries', name: 'Blue Berry Pastry', barcode: 'BR000214' },
  { id: '215', category: 'Pastries', name: 'Blueberry Cheese Pastry', barcode: 'BR000215' },
  { id: '216', category: 'Pastries', name: 'Chocolate Truffle Pastry', barcode: 'BR000216' },
  { id: '217', category: 'Pastries', name: 'Classic Pineapple Pastry', barcode: 'BR000217' },
  { id: '218', category: 'Pastries', name: 'Ferrero Rocher Pastry', barcode: 'BR000218' },
  { id: '219', category: 'Pastries', name: 'Kunafa Pastry', barcode: 'BR000219' },
  { id: '220', category: 'Pastries', name: 'Lotus Biscoff Cheese Pastry', barcode: 'BR000220' },
  { id: '221', category: 'Pastries', name: 'Mushroom Vol au vents', barcode: 'BR000221' },
  { id: '222', category: 'Pastries', name: 'New York Cheese Pastry', barcode: 'BR000222' },
  { id: '223', category: 'Pastries', name: 'Nutella Cheese Pastry', barcode: 'BR000223' },
  { id: '224', category: 'Pastries', name: 'Rainbow Pastry', barcode: 'BR000224' },
  { id: '225', category: 'Pastries', name: 'Red Velvet Pastry', barcode: 'BR000225' },
  { id: '226', category: 'Pizza', name: 'Farm House', barcode: 'BR000226' },
  { id: '227', category: 'Pizza', name: 'Golden Corn Delight', barcode: 'BR000227' },
  { id: '228', category: 'Pizza', name: 'Pizza Chef\'s Spl Makhani Paneer', barcode: 'BR000228' },
  { id: '229', category: 'Pizza', name: 'Pizza Classic Margarita', barcode: 'BR000229' },
  { id: '230', category: 'Pizza', name: 'Pizza Crispy Peppy Paneer', barcode: 'BR000230' },
  { id: '231', category: 'Savouries & Snacks', name: 'Butter Croissant', barcode: 'BR000231' },
  { id: '232', category: 'Savouries & Snacks', name: 'Choco Lava', barcode: 'BR000232' },
  { id: '233', category: 'Savouries & Snacks', name: 'Chocolate Croissant', barcode: 'BR000233' },
  { id: '234', category: 'Savouries & Snacks', name: 'Classic Aloo Tikki', barcode: 'BR000234' },
  { id: '235', category: 'Savouries & Snacks', name: 'Cold Sandwich', barcode: 'BR000235' },
  { id: '236', category: 'Savouries & Snacks', name: 'Cream Roll', barcode: 'BR000236' },
  { id: '237', category: 'Savouries & Snacks', name: 'Cup Cake', barcode: 'BR000237' },
  { id: '238', category: 'Savouries & Snacks', name: 'Doughnut', barcode: 'BR000238' },
  { id: '239', category: 'Savouries & Snacks', name: 'Hot Dog', barcode: 'BR000239' },
  { id: '240', category: 'Savouries & Snacks', name: 'Korean Chilli Paneer Puff', barcode: 'BR000240' },
  { id: '241', category: 'Savouries & Snacks', name: 'Mushroom Puff', barcode: 'BR000241' },
  { id: '242', category: 'Savouries & Snacks', name: 'Onion Kachori', barcode: 'BR000242' },
  { id: '243', category: 'Savouries & Snacks', name: 'Paneer Patties', barcode: 'BR000243' },
  { id: '244', category: 'Savouries & Snacks', name: 'Paneer Zinger Burger', barcode: 'BR000244' },
  { id: '245', category: 'Savouries & Snacks', name: 'Peri- Peri Paneer Burger', barcode: 'BR000245' },
  { id: '246', category: 'Savouries & Snacks', name: 'Soya Biryani Puff', barcode: 'BR000246' },
  { id: '247', category: 'Savouries & Snacks', name: 'Spicy Lava Burger', barcode: 'BR000247' },
  { id: '248', category: 'Savouries & Snacks', name: 'Stuffed Kulcha', barcode: 'BR000248' },
  { id: '249', category: 'Savouries & Snacks', name: 'Super Veggie Burger', barcode: 'BR000249' },
  { id: '250', category: 'Savouries & Snacks', name: 'Tandori Paneer Burger', barcode: 'BR000250' },
  { id: '251', category: 'Savouries & Snacks', name: 'Vada Pav', barcode: 'BR000251' },
  { id: '252', category: 'Savouries & Snacks', name: 'Wraps', barcode: 'BR000252' },
  { id: '253', category: 'Shakes', name: 'Belgium Chocolate Shake', barcode: 'BR000253' },
  { id: '254', category: 'Shakes', name: 'Chocolate Oreo Shake', barcode: 'BR000254' },
  { id: '255', category: 'Shakes', name: 'Kitkat Shake', barcode: 'BR000255' },
  { id: '256', category: 'Shakes', name: 'Mix Berry Shake', barcode: 'BR000256' },
  { id: '257', category: 'Shakes', name: 'Strawberry Shake', barcode: 'BR000257' },
];

export const PRIORITY_ITEM_NAMES = [
  'Chocolate Truffle Cake (1/2 Kg)',
  'Chocolate Truffle Cake (1 Kg)',
  'Classic Pineapple Cake (1/2 Kg - Serve 4-6)',
  'Butterscotch Cake (1/2 Kg - Serve 4-6)',
  'Vanilla Cake (1/2 Kg - Serve 4-6)',
  'Fresh Fruit Cake (1/2 Kg - Serve 4-6)',
  'Blueberry Cake (1/2 Kg - Serve 4-6)',
  'Tiramisu (Coffee Flavour) (1/2 Kg - Serve 4-6)',
  'Black Forest Cake (1/2 Kg - Serve 4-6)',
  'Red Velvet Cake (1/2 Kg - Serve 4-6)',
  'Blueberry Cheese Cake (1/2 Kg - Serve 4-6)',
  'Nutella Cheese Cake (1/2 Kg - Serve 4-6)',
  'Fresh Mango (Seasonal) Cake (1/2 Kg - Serve 4-6)',
  'Ferraro Rocher Cake (1/2 Kg - Serve 4-6)',
  'Rasmalai (1/2 Kg - Serve 4-6)',
  'Classic Pineapple Pastry',
  'Black Forest Pastry',
  'Chocolate Truffle Pastry',
  'Red Velvet Pastry',
  'Blue Berry Pastry',
  'Rainbow Pastry',
  'Biscoff Cheese Pastry',
  'Blueberry Cheese Pastry',
  'Nutella Cheese Pastry',
  'Kunafa Pastry',
  'Choco Chip Dry Cake',
  'Chocochip (1/2 Kg - Serve 4-6)',
  'Chocochip (250g)',
  'Mawa Dry Cake',
  'Mawa (1/2 Kg - Serve 4-6)',
  'Mawa (250g)',
  'Date&Walnut (250g)',
  'Alloo Patty',
  'Paneer Patties',
  'Vada Pav',
  'Mushroom Puff',
  'Hot Dog',
  'Stuffed Kulcha',
  'Apple Pie'
];

export const getCategoryWeight = (category: string): number => {
  const cat = (category || "").toLowerCase();
  // 1. Cakes
  if (cat.includes('cake') || cat.includes('jar')) return 1;
  // 2. Pastries
  if (cat.includes('pastr') || cat.includes('pie')) return 2;
  // 3. Snacks / Savouries
  if (cat.includes('savour') || cat.includes('fry') || cat.includes('nacho') || cat.includes('pizza') || cat.includes('garlic') || cat.includes('other')) return 3;
  // 4. Cookies & Namkeens & Chocolates
  if (cat.includes('cookie') || cat.includes('chip') || cat.includes('namkeen') || cat.includes('chocolat')) return 4;
  // 5. Decorations
  if (cat.includes('decor')) return 5;
  // 6. Rest
  return 6;
};
